spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bobmate?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: bobmate
    driver-class-name: org.mariadb.jdbc.Driver
  #    url: jdbc:h2:tcp://localhost/~/bobmate
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
server:
  port: 5050
